In [1]:
import numpy as np

In [2]:
#Numpy version
print(np.__version__)

1.26.4


In [4]:
#Create a null vector of size 10 (★☆☆)
print(np.zeros(10, dtype = int))

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#How to find the memory size of any array (★☆☆)
x = np.zeros(10)
print(x.size * x.itemsize)

80


In [6]:
#How to get the documentation of the numpy add function from the command line? (★☆☆
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\ak\anaconda3\envs\nazir_tutorial\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condit

In [ ]:
#Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#Create a vector with values ranging from 10 to 49 (★☆☆)
x = np.arange(10, 50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
#Reverse a vector (first element becomes last) (★☆☆)
x = np.arange(1, 20)
xb = x[::-1]
print(xb)


[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


In [ ]:
#Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
x = np.arange(9)
#print(x)
x1 = x.reshape(3, 3)
print(x1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [24]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
x = np.array([1, 2, 0, 0, 4, 0])
indixes = np.nonzero(x)
print(indixes)

(array([0, 1, 4], dtype=int64),)


In [26]:
#Create a 3x3 identity matrix (★☆☆)
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
x = np.random.randint(1, 10, size =(3,3,3))
print(x)

[[[7 7 1]
  [7 3 9]
  [8 2 5]]

 [[1 7 2]
  [7 9 7]
  [2 2 2]]

 [[1 5 8]
  [2 4 6]
  [8 8 2]]]


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
x = np.random.randint(1, 10, size = (10, 10))
#print(x)
mn = x.min()
mx = x.max()
print(f"the min is {mn} and the mx is {mx}")

the min is 1 and the mx is 9


In [ ]:
#Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
x = np.random.random((10, 10))
x1 = x.min()
x2 = x.max()
print(f"{x1} and {x2}")

0.00654352391692814 and 0.9747962078824401


In [48]:
#Create a random vector of size 30 and find the mean value (★☆☆)
x = np.random.random(30)
print(len(x))
print(x.mean())

30
0.5291302380342716


In [65]:
#Create a 2d array with 1 on the border and 0 inside (★☆☆)
x = np.zeros((3, 3))
#print(x)
x[0, :] = 1
x[1, 0] = 1
x[2, -1] = 1
x[2, 0] = 1
x[2, 1] = 1
x[1, 2] = 1
print(x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
